// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    CarbonCampsite: typeof import('./../../../../../@vite-icons/carbon/campsite.vue')['default']
    CarbonDicomOverlay: typeof import('./../../../../../@vite-icons/carbon/dicom-overlay.vue')['default']
    CarbonLanguage: typeof import('./../../../../../@vite-icons/carbon/language.vue')['default']
    CarbonLogoGithub: typeof import('./../../../../../@vite-icons/carbon/logo-github.vue')['default']
    CarbonMoon: typeof import('./../../../../../@vite-icons/carbon/moon.vue')['default']
    CarbonStar: typeof import('./../../../../../@vite-icons/carbon/star.vue')['default']
    CarbonSun: typeof import('./../../../../../@vite-icons/carbon/sun.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    README: typeof import('./src/components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkillMenu: typeof import('./src/components/SkillMenu.vue')['default']
  }
}

export {}
